name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space delimited path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "."
  config:
    description: "Path to a configuration file for the linter."
    required: false
  comment:
    description: "Create comment with summary of linter results."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install TSQLLint
      run: |
        yarn global add tsqllint > /dev/null 2>&1
      shell: bash

    - name: Run TSQLLint
      run: |
        tsqllint -p -c "${{ inputs.config }}" | tail -1
        tsqllint -v | tail -1
        tsqllint "${{ inputs.path }}" -c "${{ inputs.config }}" > .tsqllint-output || true
        cat .tsqllint-output
      shell: bash

    - name: Generate comment
      if: contains(inputs.comment, 'true')
      run: |
        warnings=`cat .tsqllint-output | tail -1`
        errors=`cat .tsqllint-output | tail -2 | head -1`
        if [[ ${warnings:0:1} == "0" && ${errors:0:1} == "0" ]]; then status=":white_check_mark:"; else status=":x:"; fi
        echo -e "## $status TSQLLint Summary\n" >> .tsqllint-output.final
        cat .tsqllint-output | tail -4 >> .tsqllint-output.final
        echo -e "\nResults for commit ${{ github.sha }}." >> .tsqllint-output.final
        echo -e "\n[Detailed results.]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> .tsqllint-output.final
        echo -e "\n:recycle: This comment has been updated with latest results." >> .tsqllint-output.final
      shell: bash

    - name: Post as comment
      if: contains(inputs.comment, 'true')
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: .tsqllint-output.final
